set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_ENV_PASSTHROUGH_UNTRACKED
  PATH
  INCLUDE
  LIB
  WindowsSdkDir
  WindowsSDKVersion
  UniversalCRTSdkDir
  UCRTVersion
)
